### ISSUE TITLE
Include Windows 11 and Mac arm64 installation manual

### ISSUE THREAD

**Issue by jpherdi** [pep-dortmund/homepage-toolbox#137]
Did anyone check the windows 11 beta yet?
For users of a Mac M1 we should also include a working manual.
Probably the installation manual will change a bit on the new windows system.
I suppose until September a couple of people will have an updated windows system.

**Comment by maxnoe** [comment]
According to what I read online windows 11 will not be released to the general public before the workshop, only pre-releases are currently done and I doubt participants will show up with insider builds of windows 11.

And if someone does, I doubt they will need detailed installation instructions.


Mac M1 should be not different to normal by then since I expect  the new conda release to support that natively (conda forge builds of python 3.9 already fully support the M1 macs)

**Comment by lewis206** [comment]
okay perfect!

**Comment by maxnoe** [comment]
We might need to keep this open for M1 mac and close it only once the next version of anaconda with support for osx-arm64 is out, currently we would need to include instructions to install from conda-forge

**Comment by jpherdi** [comment]
Has anyone an M1? Is there still a difference or is the manual now the same for both OS?

**Comment by maxnoe** [comment]
https://www.anaconda.com/blog/new-release-anaconda-distribution-now-supporting-m1

**Comment by maxnoe** [comment]
> Has anyone an M1? Is there still a difference or is the manual now the same for both OS?

Aside from downloading mambaforge for the correct platform, nothing should be different

https://github.com/conda-forge/miniforge#mambaforge

people with M1/M2 should choose macos arm64 (apple silicon)
