### ISSUE TITLE
`libxcrypt` for `biber`

### ISSUE THREAD

**Issue by SepplL** [pep-dortmund/homepage-toolbox#299]
since this seems to occur from time to time this could be something for the FAQ or frequent errors:
Install `libxcrypt` in case of non-working `biber`

`libxcrypt-compat` for Fedora and Arch
`libxcrypt` for Ubuntu

**Comment by maxnoe** [comment]
Checking, these are hard dependencies for biber to work. The only way biber works in case one hasn't explicitly installed those is  that they were already installed by something else.

Since that means they could be removed as "unneeded dependencies", we should just add them to the installation procedure explicitly

**Comment by SepplL** [comment]
Good idea. I'll create a PR
